### PR TITLE
add opinionated auth guard & interceptor

### PR DESCRIPTION
**Pull request by sfuenffinger**

### CODE REVIEW

**Comment by vinylhero** [comment]
Test comment

**Review by santam85 — APPROVED** [review]

**Comment by kirillsud** [comment]
@sfuenffinger is there any update for RADME needed for the authentication section? https://github.com/Backbase/golden-sample-app#authentication?

**Comment by santam85** [comment]
I believe Liam had updated it with the previous PR?

**Comment by kirillsud** [comment]
Yes, it is: https://github.com/Backbase/golden-sample-app/commit/c59a40ada31745fc7ef68e9c3a2be866bc26ec4c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R81. No more questions.

**Comment by kirillsud** [comment]
Stop. @sfuenffinger I've found a bug, I guess. When I click **logout** I am redirected to the login page twice in a row:

image

**Comment by kirillsud** [comment]
And also I have an empty screen for the `/select-context` page and there is no API request which posts the selected user context.

image

**Pull request merged**
